# Generated by Django 2.0.2 on 2020-06-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20190509_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '书籍信息', 'verbose_name_plural': '书籍信息'},
        ),
    ]
